// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://linfoagnpumnyczzurlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpbmZvYWducHVtbnljenp1cmxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMTc1NzgsImV4cCI6MjA1Mzc5MzU3OH0.IcWpyepyYTK172dyBaa6Dl_iQpxQsjk-liL1SOcQ_cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);